In [1]:
# 解压文件
import gzip
import os
import pickle
import numpy as np
from utils import SimpleProblem

problem formulation
$$
\begin{aligned}
\min &1/2 x^\top Qx + p^\top x \\
s.t.\quad & Ax = b\\
&Gx \leq c

\end{aligned}
$$

In [2]:
num_var = 1000
num_ineq = num_var // 2
num_eq = num_var // 2
num_examples = 1000
data_dir = f"/data1/jxxiong/DC3/datasets/QP_RHS_{num_var}_{num_ineq}_{num_eq}/"

In [3]:
def load_data(data_dir, index, valid_frac=0.03, test_frac=0.03):
    '''
    read the data from the .gz file
    the Q, p, G, c, A are the same for all the instances, only store the last one 
    the rhs and optimal solutions are the solved for each instance
    the column vectors are with shape (bs,n)
    '''
    b, X = [],[]
    
    if isinstance(index, int) or isinstance(index, np.int64):
        index = [index]

    for id in index:
        instance_name = "qp_rhs_{}.gz".format(id)
        instance_name = os.path.join(data_dir, instance_name)
        with gzip.open(instance_name, 'rb') as f:
            data_tmp = pickle.load(f)
            b.append(data_tmp['b'])
            X.append(data_tmp['x'])
            Q = data_tmp['Q']
            p = data_tmp['p'].squeeze(-1)
            G = data_tmp['G']
            c = data_tmp['c'].squeeze(-1)
            A = data_tmp['A']

    b = np.array(b).squeeze(-1)
    X = np.array(X)
    problem = SimpleProblem(Q, p, A, G, c, b, valid_frac=valid_frac, test_frac=test_frac) # 
    problem.set_Y(X)
    return problem

In [4]:
problem = load_data(data_dir, np.arange(num_examples))

with open("/data1/jxxiong/DC3/datasets/random_simple_dataset_var{}_ineq{}_eq{}_ex{}".format(num_var, num_ineq, num_eq, num_examples), 'wb') as f:
        pickle.dump(problem, f)

In [22]:
problem = load_data(data_dir, [1,2])
problem

(100, 100) (100,) (50, 100) (50, 100) (50,) (2, 50) (2, 100)


In [11]:
problem.Y.shape, problem.X.shape, problem.p.shape, problem.p.shape

(torch.Size([2, 100]),
 torch.Size([2, 50]),
 torch.Size([100]),
 torch.Size([100]))

In [12]:
problem.obj_fn(problem.Y)

tensor([-22.1974, -21.8948])

In [7]:
problem.Y[1].min(), problem.Y[1].max()

(tensor(-2.5599), tensor(0.8177))

In [16]:
problem.Y.min(), problem.Y.max()

(tensor(-3.5639), tensor(2.3663))

In [18]:
problem.calc_Y()

running osqp


array([[-2.36424657, -0.23586095, -1.69555967, ..., -2.43606814,
         1.51841909, -1.28791379],
       [-2.37986247, -0.23098241, -1.66914138, ..., -2.45697035,
         1.54640122, -1.30121073],
       [-2.33981021, -0.25891753, -1.71284583, ..., -2.44382105,
         1.46850193, -1.29863499]])

In [19]:
with open("/home/jxxiong/A-xjx/deeplde/datasets/simple/random_simple_dataset_var100_ineq50_eq50_ex10000", 'rb') as f:
        data1 = pickle.load(f)

In [20]:
data1.Y.shape, data1.X.shape, data1.p.shape, data1.p.shape

(torch.Size([10000, 100]),
 torch.Size([10000, 50]),
 torch.Size([100]),
 torch.Size([100]))

In [ ]:
    # train_dataset = TensorDataset(data.trainX)
    # valid_dataset = TensorDataset(data.validX)
    # test_dataset = TensorDataset(data.testX)

    # train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    # valid_loader = DataLoader(valid_dataset, batch_size=len(valid_dataset))
    # test_loader = DataLoader(test_dataset, batch_size=len(test_dataset))

In [ ]:
from utils import numpy_batch_loader

for idx in numpy_batch_loader(100, 20):
    print(idx)

[49 81 25 15 51  2 11 79 58 31 91 23 21 35 95 53 14  0 60 13]
[26 22 85 96 57 97 28 37  6 39 45 55 70 40 59 19 62 63 83 99]
[12 38 66 77 61 93 18 72  7 34 78 75 84 80  4 88 33 67 68 44]
[20 17  8 92 89  3 24 16 46 52 56 87 82 32 76 64 90 30 36 27]
[43  9 65 86 98 69 10 74  5 47 29 71 94 41 42 48 50 54  1 73]


In [23]:
with open("/home/jxxiong/A-xjx/deeplde/datasets/simple/random_simple_dataset_var100_ineq50_eq50_ex10000", 'rb') as f:
        data1 = pickle.load(f)
data1.Y.shape, data1.X.shape, data1.p.shape, data1.p.shape

(torch.Size([10000, 100]),
 torch.Size([10000, 50]),
 torch.Size([100]),
 torch.Size([100]))

In [25]:
data1.validX.shape, data1.validY.shape

(torch.Size([833, 50]), torch.Size([833, 100]))